spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/wecare_test
    username: wecare_test
    password: wecareTest
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
  sql:
    init:
      mode: always          # initialization-mode 대신 사용
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG