spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
  sql:
    init:
      mode: always          # initialization-mode 대신 사용
      schema-locations: classpath:schema.sql

jwt:
  secret: ${JWT_SECRET}
  refresh-token-expiration-time: ${JWT_REFRESH_EXP}
  access-token-expiration-time: ${JWT_ACCESS_EXP}

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG