spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DB_TEST_HOST}:3306/${DB_TEST_NAME}
    username: ${DB_TEST_USER}
    password: ${DB_TEST_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_TEST_HOST}
  sql:
    init:
      mode: always          # initialization-mode 대신 사용
      schema-locations: classpath:schema.sql
