name: CI/CD for Spring Boot

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create .env for test
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > wecare-backend/wecare/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> wecare-backend/wecare/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> wecare-backend/wecare/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> wecare-backend/wecare/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> wecare-backend/wecare/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> wecare-backend/wecare/.env
          echo "JWT_ACCESS_EXP=${{ secrets.JWT_ACCESS_EXP }}" >> wecare-backend/wecare/.env
          echo "JWT_REFRESH_EXP=${{ secrets.JWT_REFRESH_EXP }}" >> wecare-backend/wecare/.env

      - name: Export env vars & run tests
        run: |
          set -a
          source wecare-backend/wecare/.env
          set +a
          ./wecare-backend/wecare/gradlew clean test

      - name: Build JAR
        run: ./wecare-backend/wecare/gradlew bootJar

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest ./wecare-backend/wecare
          docker push $IMAGE_NAME:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/project
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_ACCESS_EXP=${{ secrets.JWT_ACCESS_EXP }}" >> .env
            echo "JWT_REFRESH_EXP=${{ secrets.JWT_REFRESH_EXP }}" >> .env

            docker-compose pull
            docker-compose up -d